heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

resources:
  install_script:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config: |
        # !/bin/bash
        sudo hostnamectl set-hostname --static identity.warp.lab4.eng.bos.redhat.com
        export address=`ip -4 addr show eth0 primary | awk '/inet/ {sub ("/24", "", $2); print $2}'`
        echo $address `hostname` | sudo tee -a /etc/hosts
        sudo yum -y install ipa-server bind bind-dyndb-ldap

  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: default
      image: overcloud-full
      flavor: oooq_compute
      networks:
        - network: ctlplane
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_resource: install_script}
